module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define("User", {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      allowNull: false,
      primaryKey: true,
    },
    firstName: DataTypes.STRING,
    middleName: DataTypes.STRING,
    lastName: DataTypes.STRING,
    email: DataTypes.STRING,
    contactNo: DataTypes.STRING,
    emargencyContactNo: DataTypes.STRING,
    password: DataTypes.STRING,
    employeeId: DataTypes.STRING,
    permanentAddress: DataTypes.STRING,
    currentAddress: DataTypes.STRING,
    gender: DataTypes.STRING,
    dateOfBirth: DataTypes.STRING,
    guardianName: DataTypes.STRING,
    previousCompanyName: DataTypes.STRING,
    previousCompanyDesignation: DataTypes.STRING,
    employeeImage: DataTypes.STRING,
    aadharNumber: DataTypes.STRING,
    aadharFrontImage: DataTypes.STRING,
    aadharBackImage: DataTypes.STRING,
    voterIdNo: DataTypes.STRING,
    voterIdImage: DataTypes.STRING,
    panNo: DataTypes.STRING,
    panImage: DataTypes.STRING,
    passportNo: DataTypes.STRING,
    passportImage: DataTypes.STRING,
    isAdmin: DataTypes.BOOLEAN,
    isActive: DataTypes.BOOLEAN,
    isVerified: DataTypes.BOOLEAN,
  });

  return User;
};
